/**
 *
 * $Id$
 */
package addressbook.univrouen.fr.addressbook.validation;

import addressbook.univrouen.fr.addressbook.Personne;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link addressbook.univrouen.fr.addressbook.AdressBook}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdressBookValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePersonne(EList<Personne> value);
}
