/**
 *
 * $Id$
 */
package addressbook.univrouen.fr.addressbook.validation;

import addressbook.univrouen.fr.addressbook.Adresse;

/**
 * A sample validator interface for {@link addressbook.univrouen.fr.addressbook.Personne}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonneValidator {
	boolean validate();

	boolean validateNom(String value);
	boolean validatePrenom(String value);
	boolean validateAge(int value);
	boolean validateAdresse(Adresse value);
	boolean validateIdentifier(String value);
}
